import { BreadCrumbUI, NavbarUI } from "@/components";
import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <BreadCrumbUI /> */}
        <Toaster position="bottom-center" />
        <NavbarUI />
        <div className="px-4"> {children}</div>
      </body>
    </html>
  );
}
